# This is a complexity limit checking workflow

name: CCN check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Istall lizard
        uses: pip install lizard
        
      - name: Limit complexity
        run: $HOME/.local/bin/lizard --CCN 3
