name: Build
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
  
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup msbuild.exe
      uses: microsoft/setup-msbuild@v1.0.0
    
    - name: static analysis of SCU
      run: ./Cppcheck_Config/cppcheck.exe SCUFiles/CommandLine.cpp SCUFiles/ListManagement.cpp SCUFiles/ReadImage.cpp SCUFiles/SendImage.cpp SCUFiles/SCUMain.cpp SCUFiles/SCUMainFunction.cpp --verbose --std=c++11 --language=c++ --enable=all -UEXP_FUNC
 
    - name: Build SCU test project
      run: msbuild SCUFiles/SCUTestProj.vcxproj /p:configuration=release /p:platform=x64 /p:OutDir="build_output"
 
    - name: Download MergeCom utility
      run: curl http://estore.merge.com/mergecom3/products/v5.11/mc3_w64_5110_008-91208.zip --output mc3_w64.zip
 
    - name: Unzip MergeCom
      shell: powershell
      run: Expand-Archive -Path .\mc3_w64.zip -DestinationPath mc3_w64
 
    - name: Copy required DLLs
      shell: cmd
      run: xcopy .\mc3_w64\mc3lib\*.dll .\SCUFiles\build_output\ /D
 
    - name: Testing SCU
      working-directory: SCUFiles
      shell: cmd
      run: build_output\SCUTestProj.exe

    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.8' 
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64' 
    
    - name: Adding required python modules to test DiagnosisTracker
      shell: cmd
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pytest opencv-python pandas

    - name: Testing Diagnosis Tracker
      working-directory: DiagnosisTracker
      shell: cmd
      run: pytest DiagnosisTrackerTest.py