name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
  
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup msbuild.exe
      uses: microsoft/setup-msbuild@v1.0.0
    
    - name: Build SCU
      run: msbuild SCUFiles/SCU.vcxproj /p:configuration=release /p:platform=x64
    
    - name: static analysis of SCU
      run: ./Cppcheck_Config/cppcheck.exe SCUFiles/Command_Line.cpp SCUFiles/List_Management.cpp SCUFiles/Read_Image.cpp SCUFiles/Send_Image.cpp SCUFiles/scu-main.cpp SCUFiles/scu-main-function.cpp --verbose --std=c++11 --language=c++ --enable=all
    
    - name: Cleaning SCU build folders
      run: msbuild SCUFiles/SCU.vcxproj /t:clean /p:configuration=release /p:platform=x64

    - name: Build SCU test project
      run: msbuild SCUFiles/SCUTestProj.vcxproj /p:configuration=release /p:platform=x64
